# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#mqtt configuration
mqtt:
  broker: 192.168.131.206

input_boolean:
  mqtt:
    name: "AM3_MQTT_SendCommand"

input_text:
  mqtt:
    name: "AM43_MQTT_Commands"
  schedule:
    name: "AM43_MQTT_Schedule"
  notifications:
    name: "AM43_MQTT_Notifications"
  configuration:
    name: "AM43_MQTT_Configuration"
  busy:
    name: "AM43_MQTT_BusyState"
    initial: "0"

sensor:
  - platform: time_date
    display_options:
      - "time"
  - platform: mqtt
    state_topic: "am43/notifications"
    expire_after: 1
